### ISSUE TITLE
Update README to explain couchdb-config repo

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app-server#1]
The README should explain that couchdb-config is used to configure CORS on CouchDB.

See the explanation here: https://github.com/Tour-de-Force/btc-app/issues/5

**Comment by asmasattar** [comment]
Hey Sam, 

This is good information to have. Thank you for updating! I actually think this may be causing the register/authenticate bug issues I'm personally experiencing. Looks good to me. Ship 🛳 it!

**Comment by samfalconer** [comment]
Tracking work to make a useful README in the other repo here: https://github.com/Tour-de-Force/couchdb-config/issues/1
