### ISSUE TITLE
unable to edit service name

### ISSUE THREAD

**Issue by jsieber** [Tour-de-Force/btc-app-server#17]
This is on iOS, will need to validate that it is happening on Android.
I created a new service but accidentally misspelled the name. If I try to update the service, I'm only able to update Phone Number, Address, etc. not the actual service name.  I could delete and start over again but should not have to.

**Comment by samfalconer** [comment]
Looks like an app issue. Moving to btc-app repo and closing: https://github.com/Tour-de-Force/btc-app/issues/55

**Comment by jsieber** [comment]
Sorry, not sure why I put these in the wrong repo.
