### ISSUE TITLE
Update service screen allows the selection of tabs but does not change screen.

### ISSUE THREAD

**Issue by jsieber** [Tour-de-Force/btc-app-server#18]
While trying to update a service on iOS, I'm able to move from tab to tab but the content of the screen remains on the Description page. Clicking on the hours or amenity tab highlights the tab but does not change the screen.

**Comment by samfalconer** [comment]
Looks like an app issue. Moving to btc-app repo and closing: https://github.com/Tour-de-Force/btc-app/issues/56
