### ISSUE TITLE
Account creation - Document Update conflict

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app-server#22]
From @jsieber-aca -

If a user tries to create an account with an email address that is already associated with an existng account the following error will occur, "Document update conflict". A better error message would be useful here.

I ran into this bug after creating an account that had a password that is too short. That bug is already logged.

**Comment by samfalconer** [comment]
Merging now to make the build cutoff. Leaving open for final review.

**Comment by asmasattar** [comment]
I tested it and it worked. ship 🛳 it!

**Comment by samfalconer** [comment]
Reviewed; closing (already merged).
