### ISSUE TITLE
Configure app server to use bicycletouringcompanion.com domain name

### ISSUE THREAD

**Issue by jsieber** [Tour-de-Force/btc-app-server#28]
We own the bicycletouringcompanion.com domain name. The intent was to use this for the server side and web view of the application. We should also be sending emails as this domain as well.

**Comment by asmasattar** [comment]
I looked over the code, it looks good. I could not test it, but as far as I can tell it looks ready for shipping. ship 🛳 it!

**Comment by samfalconer** [comment]
Merged.
