### ISSUE TITLE
Flyout menu shows that I'm logged in, but publish attempt says otherwise.

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app-server#47]
From jsieber-aca:

On my Android device, I ran into an issue where the Flyout menu shows that I'm logged in to the application but when I try to publish new or updated services I get an error message that I need to be logged in to publish points.

It appears that at some point my session times out and I'm no longer logged into the app even though the fly out menu shows that I'm still logged in.

These two areas should not contradict each other.
How are sessions maintained in the app? Should we be keeping a user authenticated once they login until their credentials have changed? It seems that sessions end very frequently while most mobile apps keep you logged on for a long time.

**Comment by samfalconer** [comment]
Merging to make build. Leaving open for review.

**Comment by samfalconer** [comment]
Approved by Austin in the PR. Closing.

**Comment by jsieber** [comment]
This still happens in the web view and on my Android device. My login session timeouts out after 30 minutes or so.

**Comment by samfalconer** [comment]
Caused by a series of silently failed deployments. Should be fixed once the new deployments are running.
