### ISSUE TITLE
Remove username, replace with email address 

### ISSUE THREAD

**Issue by asmasattar** [Tour-de-Force/btc-app-server#5]
Remove username from the Server Layer. We need to replace it with the user's email address. Link to btc-app, username removed from form: https://github.com/Tour-de-Force/btc-app/issues/33. Link to btc-models, username removed from models layer: https://github.com/Tour-de-Force/btc-models/issues/3.

**Comment by samfalconer** [comment]
Looks good to 🛳!

**Comment by samfalconer** [comment]
Looks good to 🛳!

**Comment by asmasattar** [comment]
Merged.
